#!/bin/env bash

# add colors to ls
os=$(uname)
case $os in
    MING*) alias ls='ls --color=auto' ;;
    Linux) alias ls='ls --color=auto';;
    Darwin) alias ls='ls -G' ;;
    *) alias ls='ls --color=auto' ;;
esac

# ls options
alias l='ls -F'
alias lR='ls -FR'
alias la='ls -a'
alias ll='ls -l'
alias llR='ls -lR'
alias llf='ll -F'
alias lll='ls -al'
alias lllR='ls -alR'
alias lllf='lll -F'

# show hidden files
alias l.='ls -d1 .*'

# make grep show colors
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# NETWORKING ALIASES
# start a simple http server
sserver() {
    local p=8080
    if [ "$#" -eq 1 ]; then
        p=$1
    fi
    printf "http://%s:%s\n" $(hostname) $p && sudo python3 -m http.server $p
}
# get local ip
alias localip='ipconfig getifaddr en0'
# mac addresses
alias macaddrs='arp -a'
# get ip
alias publicip='curl ifconfig.me'

# ssh aliases
# ucla
alias ssh115c='ssh -X culver@eeapps.seas.ucla.edu'
alias sshc='ssh culver9'
# raspberry pi zero
alias sshzi='ssh pi@$(publicip)'
alias sshz='ssh pi@raspberrypi.local'

alias c='clear'
alias e='exit'

# alias for quick changing directories
alias ghub='cd ~/GitHub/'
alias ucla='cd ~/Documents/ucla/4th\ yr/2nd\ qtr'
alias desk='cd ~/Desktop/'
alias doc='cd ~/Documents/'
alias down='cd ~/Downloads/'
alias dot='cd ~/.dotfiles/'
alias vol='cd /Volumes/'

# X11 forwarding
# export DISPLAY=:0

# alias to output path
alias path='echo $PATH | tr : \\n | sort'
alias pathu='path | uniq -c'

# alias to output fpath
alias fpath='echo $FPATH | tr : \\n | sort'
alias fpathu='fpath | uniq -c'

# keep display awake
alias nosleep='caffeinate -d'

# mac only aliases
case $os in
    Darwin)
        # replace cat with bat
        command -v bat >/dev/null && alias cat='bat'

        # brew deps tree
        alias bdt='brew deps --tree --installed'

        # update brew bundle
        alias bbd='brew bundle dump --force --describe --file=~/.dotfiles/Brewfile'

        # brew leaves
        alias bl='brew leaves'

        # update and clean up packages on mac
        macupdate() {
            echo "===deactivating conda env===" | fmt -c -w $COLUMNS &&
            conda deactivate &&
            echo "===brew commands===" | fmt -c -w $COLUMNS &&
            brew update &&
            brew upgrade &&
            brew cleanup --prune=all &&
            if ! brew doctor
            then
                echo "===FAIL===brew doctor===" | fmt -c -w $COLUMNS
            fi
            echo "===conda commands===" | fmt -c -w $COLUMNS &&
            conda activate &&
            conda upgrade conda -y &&
            conda update --all -y &&
            conda clean --all -y &&
            echo "===success===" | fmt -c -w $COLUMNS &&
            brewDeps=$(brew leaves --installed-as-dependency)
            if [[ $(printf "%s" ${brewDeps} | wc -l) -ne 0 ]]
            then
                echo "===uninstall the following===" | fmt -c -w $COLUMNS &&
                echo ${brewDeps}
            fi
            unset brewDeps
        }

        # nibble compile
        nibblec() {
            pushd ~/GitHub/qmk_firmware &&
            if make nullbitsco/nibble:$1
            then
                lllf *.hex
            fi
            popd
        }

        # nibble directory
        alias nibbled='ghub && cd qmk_firmware/keyboards/nullbitsco/nibble/'

        # enable airport utility
        alias airport='/Sy*/L*/Priv*/Apple8*/V*/C*/R*/airport'

        # alias to find wifi name
        alias wifiname='airport -I | grep -E "\s+SSID:"'

        ;;
esac

# json format
alias jsonformat='python3 -m json.tool'

# make tree output in color
alias tree='tree -C'
