#!/bin/env bash
# ~/.dotfiles/aliasrc
#     __      __  ______
#    /\ \  __/\ \/\  __  \
#    \ \ \/\ \ \ \ \ \_\  \
#     \ \ \ \ \ \ \ \  _  /
#      \ \ \_/ \_\ \ \ \\  \
#       \ \____^___/\ \_\ \_\
#         \/__//__/  \/_/\/_/
################################################################################

os=$(uname)
case $os in
Darwin)
    ###########
    # MAC ALIAS
    ###########
    alias ls='ls -G'
    command -v bat >/dev/null && alias cat='bat'
    alias bdt='brew deps --tree --installed'
    alias bbd='brew bundle dump --force --describe --file=~/.dotfiles/Brewfile'
    alias bl='brew leaves'
    alias airport='/Sy*/L*/Priv*/Apple8*/V*/C*/R*/airport'
    alias wifiname='airport -I | grep -E "\s+SSID:"'
    alias vol='cd /Volumes/'
    ###########
    # FUNCTIONS
    ###########
    manpdf() { man -t "${1}" | open -f -a /System/Applications/Preview.app/; }
    centerandcolor() {
        echo -n "\e[1m" && # begin bold
            case $2 in
            blue) echo -n "\e[34m" ;;
            red) echo -n "\e[31m" ;;
            green) echo -n "\e[32m" ;;
            dgray) echo -n "\e[90m" ;;
            lgray) echo -n "\e[37m" ;;
            esac
        echo -n "===$1===" | fmt -c -w $COLUMNS &&
            echo -n "\e[0m" # end color
    }
    macupdate() {
        centerandcolor "deactivating conda environment" dgray &&
            conda deactivate &&
            centerandcolor "brew commands" dgray &&
            centerandcolor "brew update" blue &&
            brew update &&
            centerandcolor "brew upgrade" blue &&
            brew upgrade &&
            centerandcolor "brew cleanup" blue &&
            brew cleanup --prune=all &&
            centerandcolor "brew autoremove" blue &&
            brew autoremove &&
            centerandcolor "brew doctor" blue &&
            if ! brew doctor; then
                centerandcolor "FAIL brew doctor" red
            fi
        centerandcolor "conda commands" dgray &&
            conda activate &&
            centerandcolor "conda update" blue &&
            conda update --all -y &&
            centerandcolor "conda clean" blue &&
            conda clean --all -y &&
            centerandcolor "success" green &&
            brewDeps=$(brew leaves --installed-as-dependency)
        if [[ $(printf "%s" "${brewDeps}" | wc -l) -ne 0 ]]; then
            centerandcolor "uninstall the following" red &&
                echo "${brewDeps}"
        fi
        unset brewDeps
    }
    ####################
    # KEYBOARD COMPILING
    ####################
    nibblecompile() {
        pushd ~/GitHub/qmk_firmware &&
            if make nullbitsco/nibble:"$1"; then
                lllf -- *.hex
            fi
        popd || exit 1
    }
    alias nibblecd='ghub && cd qmk_firmware/keyboards/nullbitsco/nibble/'
    #########
    # EXPORTS
    #########
    # FZF
    export FZF_DEFAULT_COMMAND='fd --type f --hidden'
    export FZF_ALT_C_COMMAND="fd --type d --hidden"
    export FZF_ALT_C_OPTS="--preview 'tree -C -L 2 {} | head -50'"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :50 {}'"
    # X11 forwarding
    # export DISPLAY=:0
    ;;
*) alias ls='ls --color=auto' ;;
esac

################################################################################
# ALIASES
################################################################################
# shellcheck disable=SC2142
alias l.='ls --color=always -Ald .* | awk "{print \$9 \$10 \$11}"'
alias l='ls -AF'
alias ll='ls -lF'
alias lll='ls -AlF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias localip='ipconfig getifaddr en0'
alias macaddrs='arp -a'
alias publicip='curl ifconfig.me'
alias ssh115c='ssh -X culver@eeapps.seas.ucla.edu'
alias sshc='ssh culver9'
alias sshzi='ssh pi@$(publicip)'
alias sshz='ssh pi@raspberrypi.local'
alias c='clear'
alias e='exit'
alias ghub='cd ~/GitHub/'
alias ucla='cd ~/Documents/ucla/4th\ yr/3rd\ qtr'
alias team3='cd ~/GitHub/Team3/'
alias desk='cd ~/Desktop/'
alias doc='cd ~/Documents/'
alias down='cd ~/Downloads/'
alias dot='cd ~/.dotfiles/'
alias path='echo $PATH | tr : \\n | sort'
alias pathu='path | uniq -c'
alias fpath='echo $FPATH | tr : \\n | sort'
alias fpathu='fpath | uniq -c'
alias nosleep='caffeinate -d'
alias jsonformat='python3 -m json.tool'
alias tree='tree -C'
alias gr='cd $(git rev-parse --show-toplevel)'

################################################################################
# FUNCTIONS
################################################################################
sserver() {
    local p=8080
    printf "http://%s:%s\n" "$(hostname)" "$p" && sudo python3 -m http.server "$p"
}

# https://github.com/termstandard/colors
colortest() {
    awk 'BEGIN{
        s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
        for (colnum = 0; colnum<77; colnum++) {
            r = 255-(colnum*255/76);
            g = (colnum*510/76);
            b = (colnum*255/76);
            if (g>255) g = 510-g;
            printf "\033[48;2;%d;%d;%dm", r,g,b;
            printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
            printf "%s\033[0m", substr(s,colnum+1,1);
        }
        printf "\n";
    }'
}
randfig() {
    figlet -f "$(find "$(brew --prefix figlet)"/share/figlet/fonts/*.flf -type f | sort -R | head -1)" "$@"
}
