#!/bin/env bash
# ~/.dotfiles/aliasrc
#     __      __  ______
#    /\ \  __/\ \/\  __  \
#    \ \ \/\ \ \ \ \ \_\  \
#     \ \ \ \ \ \ \ \  _  /
#      \ \ \_/ \_\ \ \ \\  \
#       \ \____^___/\ \_\ \_\
#         \/__//__/  \/_/\/_/
################################################################################

os=$(uname)
case $os in
Darwin)
    ###########
    # MAC ALIAS
    ###########
    alias bdt='brew deps --tree --installed'
    alias bbd='brew bundle dump --force --describe --file=~/.dotfiles/Brewfile'
    alias bl='brew leaves'
    alias airport='/Sy*/L*/Priv*/Apple8*/V*/C*/R*/airport'
    alias wifiname='airport -I | grep -E "\s+SSID:"'
    alias vol='cd /Volumes/'
    ###########
    # FUNCTIONS
    ###########
    manpdf() { man -t "${1}" | open -f -a /System/Applications/Preview.app/; }
    centerandcolor() {
        echo -n "\e[1m" && # begin bold
            case $2 in
            blue) echo -n "\e[34m" ;;
            red) echo -n "\e[31m" ;;
            green) echo -n "\e[32m" ;;
            dgray) echo -n "\e[90m" ;;
            lgray) echo -n "\e[37m" ;;
            esac
        echo -n "===$1===" | fmt -c -w $COLUMNS &&
            echo -n "\e[0m" # end color
    }
    macupdate() {
        centerandcolor "deactivating conda environment" dgray &&
            conda deactivate &&
            centerandcolor "brew commands" dgray &&
            centerandcolor "brew update" blue &&
            brew update &&
            centerandcolor "brew upgrade" blue &&
            brew upgrade &&
            centerandcolor "brew cleanup" blue &&
            brew cleanup --prune=all &&
            centerandcolor "brew autoremove" blue &&
            brew autoremove &&
            centerandcolor "brew doctor" blue &&
            if ! brew doctor; then
                centerandcolor "FAIL brew doctor" red
            fi
        centerandcolor "conda commands" dgray &&
            conda activate &&
            centerandcolor "conda update" blue &&
            conda update --all -y &&
            centerandcolor "conda clean" blue &&
            conda clean --all -y &&
            centerandcolor "success" green &&
            brewDeps=$(brew leaves --installed-as-dependency)
        if [[ $(printf "%s" "${brewDeps}" | wc -l) -ne 0 ]]; then
            centerandcolor "uninstall the following" red &&
                echo "${brewDeps}"
        fi
        unset brewDeps
    }
    ####################
    # KEYBOARD COMPILING
    ####################
    nibblecompile() {
        pushd ~/GitHub/qmk_firmware &&
            if make nullbitsco/nibble:"$1"; then
                lllf -- *.hex
            fi
        popd || exit 1
    }
    alias nibblecd='ghub && cd qmk_firmware/keyboards/nullbitsco/nibble/'
    #########
    # EXPORTS
    #########
    # FZF
    export FZF_DEFAULT_COMMAND='fd --type f --hidden'
    export FZF_ALT_C_COMMAND="fd --type d --hidden"
    export FZF_ALT_C_OPTS="--preview 'tree -C -L 2 {} | head -50'"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :50 {}'"
    # X11 forwarding
    # export DISPLAY=:0
    ;;
*) alias ls='ls --color=auto' ;;
esac

################################################################################
# ALIASES
################################################################################
# command dependent aliases
if command -v bat >/dev/null; then
    alias cat='bat'
    alias man='batman'
    help() { "$@" --help 2>&1 | bat --plain --language=help; }
    tailf(){ tail -f "$@" | bat --paging=never -l log; }
fi
command -v colordiff >/dev/null && alias diff='colordiff'
if command -v exa >/dev/null; then
    alias exa='exa --icons --git --color-scale --group-directories-first'
    alias ls='exa'
    alias l.='exa --sort=size -a1Fd .*'
    alias l='exa -aF'
    alias ll='exa -lF'
    alias lll='exa -alF'
    alias tree='exa --tree'
else
    # shellcheck disable=SC2142
    alias l.='ls --color=always -Ald .* | awk "{print \$9 \$10 \$11}"'
    alias l='ls -AF'
    alias ll='ls -lF'
    alias lll='ls -AlF'
fi

alias c='clear'
alias desk='cd ~/Desktop/'
alias doc='cd ~/Documents/'
alias dot='cd ~/.dotfiles/'
alias down='cd ~/Downloads/'
alias e='exit'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias fpath='echo $FPATH | tr : \\n | sort'
alias fpathu='echo $FPATH | tr : \\n | sort | uniq -c'
alias ghub='cd ~/GitHub/'
alias gr='cd $(git rev-parse --show-toplevel)'
alias grep='grep --color=auto'
alias jsonformat='python3 -m json.tool'
alias localip='ipconfig getifaddr en0'
alias macaddrs='arp -a'
alias nosleep='caffeinate -d'
alias path='echo $PATH | tr : \\n | sort'
alias pathu='echo $PATH | tr : \\n | sort | uniq -c'
alias publicip='curl ifconfig.me'
alias sshz='ssh pi@raspberrypi.local'
alias sshzi='ssh pi@$(curl ifconfig.me)'
alias team3='cd ~/GitHub/Team3/'

################################################################################
# FUNCTIONS
################################################################################
sserver() {
    local p=8080
    printf "http://%s:%s\n" "$(hostname)" "$p" && sudo python3 -m http.server "$p"
}

# https://github.com/termstandard/colors
colortest() {
    awk 'BEGIN{
        s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
        for (colnum = 0; colnum<77; colnum++) {
            r = 255-(colnum*255/76);
            g = (colnum*510/76);
            b = (colnum*255/76);
            if (g>255) g = 510-g;
            printf "\033[48;2;%d;%d;%dm", r,g,b;
            printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
            printf "%s\033[0m", substr(s,colnum+1,1);
        }
        printf "\n";
    }'
}
randfig() {
    figlet -f "$(find "$(brew --prefix figlet)"/share/figlet/fonts/*.flf -type f | sort -R | head -1)" "$@"
}

pickfig() {
    figlet -f "$(find "$(brew --prefix figlet)"/share/figlet/fonts/*.flf -type f | fzf --preview="figlet -f {} $1")" "$1"
}

################################################################################
# EXPORTS
################################################################################
export TERM=xterm-256color
export CLICOLOR=1
# https://geoff.greer.fm/lscolors/
# https://mybyways.com/blog/macos-zsh-configuration
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
